import Head from "next/head";
import HomePage from "./home";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Bank App</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@700&display=swap" rel="stylesheet" />
      </Head>

      <main>
        <HomePage />
      </main>
    </div>
  );
}
